import './globals.css'
import Navbar from '../components/Navbar'
import FooterPage from '@/components/footer'
import Prviderredux from '../redux/prvider'
import {Toaster } from 'react-hot-toast'
import Proidernextauth from './provider'
export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
         <Prviderredux>
          <Proidernextauth>
         <Navbar />
         {children}
         <FooterPage/>
         </Proidernextauth>
         </Prviderredux>
         <Toaster  position='top-right'/>
        </body>
    </html>
  )
}
